
version: '2.1'
services:
  waitforit:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_FILESERVER=${IMAGE_ARG_FILESERVER:-http://o9wbz99tz.bkt.clouddn.com}
      - IMAGE_ARG_WAITFORIT_VERSION=${IMAGE_ARG_WAITFORIT_VERSION:-2.2.0}
    image: ${IMAGE_PREFIX:-cirepo}/waitforit:${IMAGE_TAG:-2.2.0}
